### ISSUE TITLE
Lmod cache for EESSI software

### ISSUE THREAD

**Issue by ocaisa** [EESSI/software-layer#10]
We should probably create an Lmod spider cache alongside our software stack so that users don't have to build one the first time they try things out (which will make things look clunky when they're really not).

We need to have a script/readme for this on the client side since they may use their own MNS.

**Comment by bedroge** [comment]
This can be done by running the emerge command like:
```
EXTRA_ECONF="--with-spiderCacheDir=/path/to/cacheDir --with-updateSystemFn=/path/to/system.txt" emerge app-admin/Lmod
```

**Comment by boegel** [comment]
That's not enough, we need to update the Lmod cache every time we add module files too...

**Comment by boegel** [comment]
Also, it makes sense to have a separate module cache for each part of the repo (one for `inte/lhaswell`, one for `amd/zen2`, etc.)

**Comment by bedroge** [comment]
Yeah, I know, this was just for the installation part.

**Comment by boegel** [comment]
There's actually nothing special needed at installation time, you can configure Lmod at runtime via environment variables w.r.t. the spider cache location.

**Comment by bedroge** [comment]
Oh, okay, didn't know that. Thought it had to be enabled during the installation as well.

**Comment by bedroge** [comment]
I was reading something about CVMFS server hooks yesterday, maybe we could use those for generating the module cache (by automatically running the update script(s) each time something gets published)?

https://github.com/cvmfs/cvmfs/blob/devel/cvmfs/cvmfs_server_hooks.sh.demo

I'm just not sure if this also gets called on the Stratum 0 if we use publisher nodes; otherwise the publisher nodes probably need a copy of the hooks script themselves.

**Comment by boegel** [comment]
I think it's better if the Lmod cache update is done as a part of the script we will use to install additional software (since there we can also "verify" that the installation worked)

**Comment by ocaisa** [comment]
We can also use an eb hook to trigger the Lmod cache update.

I think the problem would be that all of the installations are then targeting the same file and I'd be worried there might be something of a race condition. Probably it needs to be done daily (hourly?) with some kind of cron job and only pushed if it changes.
