### ISSUE TITLE
Warnings during first run of singularity with pilot repo

### ISSUE THREAD

**Issue by robberteggermont** [EESSI/software-layer#12]
This was a "clean" first run of singularity with the pilot repo. The warnings are highlighted (in bold). (Not sure if they can or need to be silenced.)

$ singularity shell --fusemount "$EESSI_CONFIG" --fusemount "$EESSI_PILOT" docker://eessi/client-pilot:centos7-2020.08
INFO:    Converting OCI blobs to SIF format
INFO:    Starting build...
Getting image source signatures
Copying blob 9b4ebb48de8d done  
Copying blob a56d549385a9 done  
Copying blob bb72cebcd924 done  
Copying blob 1fe06a00e459 done  
Copying blob 2fa4ed62da12 done  
Copying config 1428b00751 done  
Writing manifest to image destination
Storing signatures
2020/09/02 17:06:23  info unpack layer: sha256:9b4ebb48de8dbb85a3d9fbdec4d28a3e2e14912f27b7234c10c1658a05c320a5
**2020/09/02 17:06:24  warn rootless{usr/bin/newgidmap} ignoring (usually) harmless EPERM on setxattr "security.capability"
2020/09/02 17:06:24  warn rootless{usr/bin/newuidmap} ignoring (usually) harmless EPERM on setxattr "security.capability"
2020/09/02 17:06:24  warn rootless{usr/bin/ping} ignoring (usually) harmless EPERM on setxattr "security.capability"**
2020/09/02 17:06:30  warn rootless{usr/sbin/arping} ignoring (usually) harmless EPERM on setxattr "security.capability"
2020/09/02 17:06:30  warn rootless{usr/sbin/clockdiff} ignoring (usually) harmless EPERM on setxattr "security.capability"
2020/09/02 17:06:35  info unpack layer: sha256:a56d549385a9cdfc1c3901503a945d57c5d80ef68bbc26afc8346ad521095be9
2020/09/02 17:06:35  info unpack layer: sha256:bb72cebcd92445bcd030cc81fa11657d5fabee3b88e7a4266ea88e608f1115a5
**2020/09/02 17:06:36  warn rootless{usr/bin/wall} ignoring (usually) harmless EPERM on setxattr "user.rootlesscontainers"**
2020/09/02 17:06:46  info unpack layer: sha256:1fe06a00e459196bffdd8cfd539daf1072b3fc7900a3a641b66e5a109c8f7fa1
2020/09/02 17:06:46  info unpack layer: sha256:2fa4ed62da1263d3b93dd8e5205c8d8e1549d237e2ce0f6d15725e2007a13c06
INFO:    Creating SIF file...
Singularity> CernVM-FS: pre-mounted on file descriptor 3
CernVM-FS: pre-mounted on file descriptor 3
**Failed to set requested number of open files, using maximum number 4096**
CernVM-FS: loading Fuse module... done
**fuse: failed to clone device fd: Inappropriate ioctl for device
fuse: trying to continue without -o clone_fd.
Failed to set requested number of open files, using maximum number 4096**
CernVM-FS: loading Fuse module... done
**fuse: failed to clone device fd: Inappropriate ioctl for device
fuse: trying to continue without -o clone_fd.**

**Comment by boegel** [comment]
The `EPERM on setxattr` warnings can't be fixed afaik, but are safe to ignore, see https://umo.ci/quick-start/rootless/ .

I'm not sure how to avoid the `number of open files` issue, I guess that's in the cvmfs client config @bedroge?

The `-o clone_fd` is a known problem, but should also be harmless (it may affect performance), see https://github.com/hpcng/singularity/issues/5206#issuecomment-613637632

**Comment by bedroge** [comment]
There is indeed a `CVMFS_NFILES`, the default is in `/etc/cvmfs/default.conf`:
```
CVMFS_NFILES=65536
```

I guess `ulimit -n` is set to 4096?

**Comment by robberteggermont** [comment]
```
Singularity> ulimit -n
1024
```

**Comment by bedroge** [comment]
Can you try making a local file named `default.local` with the following content:
```
CVMFS_QUOTA_LIMIT=10000
CVMFS_HTTP_PROXY="DIRECT"
CVMFS_NFILES=1024
```
(or maybe even lower, e.g. 512?)
Then run singularity with an additional flag to override the file in the container with your custom file:
```
-B ./default.local:/etc/cvmfs/default.local
```
Does that solve the issue?

**Comment by robberteggermont** [comment]
Yes, that silences the "Failed to set requested number of open files, using maximum number 4096" warning.

```
$ cat default.local 
CVMFS_QUOTA_LIMIT=10000
CVMFS_HTTP_PROXY="DIRECT"
CVMFS_NFILES=1024
$ singularity shell -B ./default.local:/etc/cvmfs/default.local --fusemount "$EESSI_CONFIG" --fusemount "$EESSI_PILOT" docker://eessi/client-pilot:centos7-2020.08
INFO:    Using cached SIF image
Singularity> CernVM-FS: pre-mounted on file descriptor 3
CernVM-FS: pre-mounted on file descriptor 3
CernVM-FS: loading Fuse module... done
fuse: failed to clone device fd: Inappropriate ioctl for device
fuse: trying to continue without -o clone_fd.
CernVM-FS: loading Fuse module... done
fuse: failed to clone device fd: Inappropriate ioctl for device
fuse: trying to continue without -o clone_fd.
```

**Comment by bedroge** [comment]
As Kenneth pointed out, I'm not sure if we can do anything about these warnings at the moment. Just to be sure: despite these warnings, does the container function properly, i.e., can you access the /cvmfs repositories?

**Comment by robberteggermont** [comment]
Yes, I can access /cvmfs and run programs.

 (I had one issue that I couldn't directly related to these warnings, and I couldn't reproduce it either: a file had extra HTML code in it before the actual content. After a restart of singularity the problem was gone. Just mentioning it in case your recognize it?)

Should I close the issue?

**Comment by bedroge** [comment]
That's probably the original `/etc/cvmfs/default.local` you're referring too? We found out about some weird output in that file yesterday, and @boegel fixed it yesterday (probably somewhere between your attempts, I guess).

The issue/warning about the number of open files was not a critical one either? In that case, I was going to say that we should maybe just mention something about these warning in the docs. But I see that there's already this:

```It is possible that you see some scary looking warnings, but those can be ignored for now```

So maybe that's good enough ;-), and then I'd say that we could close the issue.

**Comment by robberteggermont** [comment]
It seems to work, only warnings, nothing critical, so I'll close this issue.
