### ISSUE TITLE
Filter LD_LIBRARY_PATH 

### ISSUE THREAD

**Issue by bedroge** [EESSI/software-layer#13]
We should set:
```
filter-env-vars=LD_LIBRARY_PATH
```
in our Easybuild configuration, to prevent (system) tools from picking up libraries from modules, which will result in nasty errors.

**Comment by boegel** [comment]
Examples: tools like `vi`, `nano`, `sed` are broken:

```
[EESSI pilot 2020.08] $ vi --version
vi: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by /cvmfs/pilot.eessi-hpc.org/2020.08/compat/x86_64/lib/../lib64/libpthread.so.0)
```

Just running `unset LD_LIBRARY_PATH` should fix those problems, the software provided through modules in the 2020.08 pilot stack should keep working (it doesn't rely on `$LD_LIBRARY_PATH` because everything is linked with RPATH).
