### ISSUE TITLE
Script to build software stack to be used by EESSI bot

### ISSUE THREAD

**Issue by trz42** [EESSI/software-layer#181]
A script `bot-build.sh` could handle all environment settings etc and would thereby make the build script of the EESSI bot (`eessi-bot-build.slurm`) simpler.

See original post by @boegel in https://github.com/EESSI/eessi-bot-software-layer/pull/10#discussion_r894926732

**Comment by trz42** [comment]
@boegel I think this can be closed as well (#233 should fix it)?

**Comment by boegel** [comment]
Agreed, closing!
