### ISSUE TITLE
Script for detecting EESSI_SOFTWARE_SUBDIR expects intel hardware.

### ISSUE THREAD

**Issue by terjekv** [EESSI/software-layer#19]
This is a bit broken, even if my CPUs have empty fields for everything that helps with detection:
```
terjekv@arm1:~/compatibility-layer$ python3 -c "import archspec.cpu, os; host_cpu = archspec.cpu.host(); vendors = {'GenuineIntel': 'intel'}; print(os.path.join(host_cpu.family.name, vendors.get(host_cpu.vendor), host_cpu.name))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/cvmfs/pilot.eessi-hpc.org/2020.09/compat/aarch64/usr/lib/python-exec/python3.7/../../../lib/python3.7/posixpath.py", line 94, in join
    genericpath._check_arg_types('join', a, *p)
  File "/cvmfs/pilot.eessi-hpc.org/2020.09/compat/aarch64/usr/lib/python-exec/python3.7/../../../lib/python3.7/genericpath.py", line 153, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'NoneType'
```

**Comment by boegel** [comment]
For non-x86_64 processors we should probably skip the `vendor` subdir?

**Comment by terjekv** [comment]
There is a maze of arm architecture pitfalls (32bit, v7s, lacking instruction sets etc), but none of that is even remotely on our radar, is it? If you want to run EESSI on your PI, well, we may have to disappoint you?

**Comment by boegel** [comment]
Certainly short term, yes. But the init script should handle that gracefully, and just say something like "Host architecture not supported" or something like that...

**Comment by terjekv** [comment]
We could, technically, provide a list of supported architectures for each "release" and modify the load script if required. A rebuild will happen for new releases anyway.

**Comment by boegel** [comment]
We don't need to have a subdirectory for each specific architecture though, that's part of the point of using `archspec`, which can pick the best suited subdir to use. If we have a stack of installations for `haswell`, any `x86_64` processor newer than that is basically supported.

So we should just ask `archspec` if it can find the best suited stack that would work on the host processor, and if it can't find any produce a clear error message.

**Comment by boegel** [comment]
Fixed in https://github.com/EESSI/software-layer/pull/22
