### ISSUE TITLE
single script and container which serve both use and build scenarios

### ISSUE THREAD

**Issue by trz42** [EESSI/software-layer#214]
Accessing the EESSI pilot software stack via a container differs when the software is just used (read-only access) or when software is built to be added (read & write access). 

For building the container available from `docker://ghcr.io/eessi/build-node:debian10` is used. For read only access the container available from `docker://ghcr.io/eessi/client-pilot:centos7` is used.

For just using the EESSI pilot (read-only access), the container used for building should be usable too. In that case one could provide a single script that serves both scenarios - either read-only access or read & write access. Similar to the `build_container.sh` script it could execute another script (or command) or provide an interactive shell.

Example runs of the script could be:

- `eessi_container.sh --access RO --mode SHELL`
- `eessi_container.sh --access RO --mode EXEC some_workload.sh`
- `eessi_container.sh --access RW --mode SHELL`
- `eessi_container.sh --access RW --mode EXEC install_package.sh`

Default settings could be `--access RO` and `--mode SHELL`.

Each invocation might have additional parameters such as `--new-tmp TMP_SPACE` or `--previous-tmp TMP_SPACE` which would enable a fresh run (`--new-tmp`) or reusing results from a previous run (`--previous-tmp`, particularly useful for incrementally building or debugging sessions).

The script could also enable to access several or specific CernVM-FS repositories, for example, adding parameters `--repository REPO` (e.g., `dev.eessi.io`), `--repository-version VERSION` (e.g., `2023.01`) and `--repository-config CFG_FILE` (e.g., providing all files necessary to access the repository - usually a public key, a `default.local` and a `<repo-domain>.conf`). Thus, any repository could be easily accessed. The implementation of that would be simplified by providing a solution to #207

**Comment by boegel** [comment]
@trz42 This can be closed now that #216 is merged?

**Comment by trz42** [comment]
Closing as suggested.
