### ISSUE TITLE
OpenFOAM 8 in broadwell tree broken

### ISSUE THREAD

**Issue by bedroge** [EESSI/software-layer#25]
By running our OpenFOAM test script on broadwell, I found that lots of files are missing in the installation folder, especially in the tutorials folder, e.g. the following dirs are completely empty (and shouldn't be):
```
/cvmfs/pilot.eessi-hpc.org/2020.09/software/x86_64/intel/broadwell/software/OpenFOAM/8-foss-2020a/OpenFOAM-8/tutorials/resources/geometry/

/cvmfs/pilot.eessi-hpc.org/2020.09/software/x86_64/intel/broadwell/software/OpenFOAM/8-foss-2020a/OpenFOAM-8/tutorials/incompressible/simpleFoam/motorBike/system/

/cvmfs/pilot.eessi-hpc.org/2020.09/software/x86_64/intel/broadwell/software/OpenFOAM/8-foss-2020a/OpenFOAM-8/tutorials/resources/blockMesh/
```

and more...

The pilot build script did crash at some point, probably during the installation of OpenFOAM. Could it be that a reinstall for OpenFOAM does something weird due to building in the installation dir?

**Comment by bedroge** [comment]
Fixed it for now by recompiling OpenFOAM. Maybe we can still test what happens if you abort an OpenFOAM installation somewhere near the end, and try to reinstall it?

**Comment by boegel** [comment]
We now run a tutorial case in the sanity check for OpenFOAM (see https://github.com/easybuilders/easybuild-easyblocks/pull/2201), so we should catch problems like this in the future...
