### ISSUE TITLE
Numpy picks up host GLIBC on AMD Zen2 architecture

### ISSUE THREAD

**Issue by Senui** [EESSI/software-layer#286]
Importing numpy after loading TensorFlow/2.3.1-foss-2020a-Python-3.8.2 results in the following error message:

```
Traceback (most recent call last):
  File "/cvmfs/pilot.eessi-hpc.org/versions/2021.12/software/linux/x86_64/amd/zen2/software/SciPy-bundle/2020.03-foss-2020a-Python-3.8.2/lib/python3.8/site-packages/numpy/core/__init__.py", line 24, in <module>
    from . import multiarray
  File "/cvmfs/pilot.eessi-hpc.org/versions/2021.12/software/linux/x86_64/amd/zen2/software/SciPy-bundle/2020.03-foss-2020a-Python-3.8.2/lib/python3.8/site-packages/numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File "/cvmfs/pilot.eessi-hpc.org/versions/2021.12/software/linux/x86_64/amd/zen2/software/SciPy-bundle/2020.03-foss-2020a-Python-3.8.2/lib/python3.8/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /cvmfs/pilot.eessi-hpc.org/versions/2021.12/software/linux/x86_64/amd/zen2/software/GCCcore/9.3.0/lib64/libgfortran.so.5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cvmfs/pilot.eessi-hpc.org/versions/2021.12/software/linux/x86_64/amd/zen2/software/TensorFlow/2.3.1-foss-2020a-Python-3.8.2/lib/python3.8/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/cvmfs/pilot.eessi-hpc.org/versions/2021.12/software/linux/x86_64/amd/zen2/software/TensorFlow/2.3.1-foss-2020a-Python-3.8.2/lib/python3.8/site-packages/tensorflow/python/__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "/cvmfs/pilot.eessi-hpc.org/versions/2021.12/software/linux/x86_64/amd/zen2/software/TensorFlow/2.3.1-foss-2020a-Python-3.8.2/lib/python3.8/site-packages/tensorflow/python/eager/context.py", line 29, in <module>
    import numpy as np
  File "/cvmfs/pilot.eessi-hpc.org/versions/2021.12/software/linux/x86_64/amd/zen2/software/SciPy-bundle/2020.03-foss-2020a-Python-3.8.2/lib/python3.8/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/cvmfs/pilot.eessi-hpc.org/versions/2021.12/software/linux/x86_64/amd/zen2/software/SciPy-bundle/2020.03-foss-2020a-Python-3.8.2/lib/python3.8/site-packages/numpy/core/__init__.py", line 54, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.8 from "/usr/bin/python3",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.18.3" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /cvmfs/pilot.eessi-hpc.org/versions/2021.12/software/linux/x86_64/amd/zen2/software/GCCcore/9.3.0/lib64/libgfortran.so.5)

```

I believe this numpy should have picked up the glibc library from the EESSI software stack. I suspect it's an issue similar to https://github.com/EESSI/software-layer/issues/123

Weirdly, ldd does show that the library in question (libgfortran) is linked to the glibc.so in the EESSI stack:

```
$ ldd /cvmfs/pilot.eessi-hpc.org/versions/2021.12/software/linux/x86_64/amd/zen2/software/GCCcore/9.3.0/lib64/libgfortran.so.5
	linux-vdso.so.1 (0x00007ffcecec5000)
	libquadmath.so.0 => /cvmfs/pilot.eessi-hpc.org/versions/2021.12/software/linux/x86_64/amd/zen2/software/GCCcore/9.3.0/lib64/libquadmath.so.0 (0x00007f2c0d579000)
	libm.so.6 => /cvmfs/pilot.eessi-hpc.org/versions/2021.12/compat/linux/x86_64/lib/../lib64/libm.so.6 (0x00007f2c0d49d000)
	libgcc_s.so.1 => /cvmfs/pilot.eessi-hpc.org/versions/2021.12/software/linux/x86_64/amd/zen2/software/GCCcore/9.3.0/lib64/libgcc_s.so.1 (0x00007f2c0d484000)
	libc.so.6 => /cvmfs/pilot.eessi-hpc.org/versions/2021.12/compat/linux/x86_64/lib/../lib64/libc.so.6 (0x00007f2c0d288000)
	/cvmfs/pilot.eessi-hpc.org/versions/2021.12/compat/linux/x86_64/lib64/ld-linux-x86-64.so.2 (0x00007f2c0d853000)
```

**Comment by ocaisa** [comment]
This might be related to #192 , but maybe more likely that the linker python loaded with (or at least 
the one used to load the library) is not the EESSI linker.

**Comment by ocaisa** [comment]
The answer from `ldd` will depend on whether you use the EESSI ldd or the system `ldd`, since it resolves libc based on the default configuration of the linker used. That makes me think that we should be setting a runpath to the compat layer as a back up to avoid this scenario

**Comment by Senui** [comment]
ldd is indeed the one from EESSI (as told by `which ldd`). Is there a way to temporarily override which loader is used by the python libraries to test your hypothesis?

**Comment by ocaisa** [comment]
I can't reproduce this, so this is tricky to investigate. Can you share what python interpreter you are using (`which python`)?

**Comment by Senui** [comment]
Ah.. you aren't able to reproduce it because you don't have a zen2 CPU to try it on, or it doesn't reproduce on your machine even though it has a zen2 CPU?

This is the output of `which python`:

```
/cvmfs/pilot.eessi-hpc.org/versions/2021.12/software/linux/x86_64/amd/zen2/software/Python/3.8.2-GCCcore-9.3.0/bin/python
```

**Comment by ocaisa** [comment]
Do you mean that this is _only_ the case on Zen2? If you use the generic x86 stack (or other archs) it works ok?
```
EESSI_SOFTWARE_SUBDIR_OVERRIDE="x86_64/generic" source /cvmfs/pilot.eessi-hpc.org/latest/init/bash
```

**Comment by Senui** [comment]
I initially just assumed that this was a zen2-specific issue, but now that you mentioned it I tried with the generic x86_64 stack, and it give the same issue. So it seems to be something related to my OS/setup.

I'm trying this on an Openstack based VM by the way - not sure if that makes a difference. Let me know if there is anything I can provide to help debug this.

**Comment by Senui** [comment]
Ok so I found out that even though `which python` shows to use the Python from the EESSI stack, it in fact uses the host's Python, which is why I get the error. If I explicitly use the absolute path of the EESSI stack's Python, there is no issue.

The `python3.8` binary however does correctly resolve to the EESSI stack one, and I don't need to specify the absolute path if I use `python3.8 -c 'import numpy'`

So in summary:

❌ `python -c 'import numpy'`
✅ `/cvmfs/pilot.eessi-hpc.org/versions/2021.12/software/linux/x86_64/amd/zen2/software/Python/3.8.2-GCCcore-9.3.0/bin/python -c 'import numpy'`
✅ `python3.8 -c 'import numpy'`

I checked the contents of the PATH envar and /cvmfs/pilot.eessi-hpc.org/versions/2021.12/software/linux/x86_64/amd/zen2/software/Python/3.8.2-GCCcore-9.3.0/bin is in front of the system paths, so shouldn't it take that one first?

**Comment by ocaisa** [comment]
The only thing I can think of is that that there is shell function ghosting `python`?

**Comment by Senui** [comment]
It turned out to be an alias. Found it out by running `type -a python`, which showed:

```
python is aliased to `/usr/bin/python3'
python is /cvmfs/pilot.eessi-hpc.org/versions/2021.12/software/linux/x86_64/amd/zen2/software/Python/3.8.2-GCCcore-9.3.0/bin/python
python is /cvmfs/pilot.eessi-hpc.org/versions/2021.12/compat/linux/x86_64/usr/bin/python
```

There was the following line in /etc/bash.bashrc

```
alias python='/usr/bin/python3'
```

I am still confused why an alias trumps what is found through PATH, and why `which python` shows that it leads to the EESSI python.

After removing that alias and logging back in, there is no issue anymore.

That alias is made as part of an Ansible routine that sets up the VM. Going to investigate why we do so in the first place. 

But maybe a good lesson learned that aliases could potentially mess up the EESSI compat layer?

**Comment by ocaisa** [comment]
Well, the alias trumping is not surprising, otherwise you would never be able to wrap anything. I expect is just looking at the environment and not the shell used.

It is an interesting point in general though, we should have that in our typical questions to ask people: if you run with full path do you still see the same problem.

**Comment by Senui** [comment]
Agreed. Many thanks for thinking along! I will close this issue then.

**Comment by trz42** [comment]
We had some issues with `which` not working when running in the prefix. The reason for this was that `which` was actually an alias

```
alias which='alias | /usr/bin/which --tty-only --read-alias --show-dot --show-tilde'
```

I think this breaks sanity checks when building intel compilers on top of EESSI.

If you need an alias for `python` when running Ansible, maybe setting the interpreter solves the issue? You can add this to a specific task with (path to python may be different in your case)
```yaml
  vars:
    ansible_python_interpreter: "{{ gentoo_prefix_path }}/usr/bin/python3"
```
_or_ globally
```yaml
- name: Set Ansible Python interpreter to the Prefix one
  ansible.builtin.set_fact:
    ansible_python_interpreter: "{{ gentoo_prefix_path }}/usr/bin/python3"
```

**Comment by boegel** [comment]
Rather than using `which`, you can also check with `command -v`:

```
$ command -v python
alias python=/usr/bin/python3
```
