### ISSUE TITLE
Hooks should be defined in SitePackage.lua, not in lmodrc.lua

### ISSUE THREAD

**Issue by casparvl** [EESSI/software-layer#491]
Defining hooks in `lmodrc.lua` works _if_ the `lmodrc.lua` files are read early enough in the process of a `module load`. However, https://github.com/EESSI/software-layer/pull/490#issuecomment-1980679090 shows that this is only the case under certain circumstances, and by no way a guarantee. We should probably move registration of the hooks to `SitePackage.lua`, as this is the officially document location for hooks https://lmod.readthedocs.io/en/latest/170_hooks.html?highlight=hook#hook-functions

**Comment by ocaisa** [comment]
The positive thing is we should still be able to do that in a way that allows sites to customise the hooks.

We can point to _our_ `SitePackage.lua` by setting `LMOD_PACKAGE_PATH=/path/to/the/Site/Directory`, and this can leverage hooks from the equivalent location under `host_injections`. @casparvl noted that changing `LMOD_PACKAGE_PATH` does not seem to require reconfiguring Lmod, so we can still have dynamic behaviour.

**Comment by casparvl** [comment]
In fact, it's mostly a renaming exercise: our `create_lmodrc.py` (for now), only writes hooks. I.e. what it creates is _actually_ a `SitePackage.lua`. If we just name it that, park it in `$EESSI_SOFTWARE_PATH/.lmod` (where we now also put the `lmodrc.lua` and set
```
export LMOD_PACKAGE_PATH="$EESSI_SOFTWARE_PATH/.lmod"
```
We're done. We do need to probably make sure that `LMOD_CONFIG_DIR` does not get set, and/or that the existing `lmodrc.lua` files get removed from the repository.
