### ISSUE TITLE
Use all binaries from the compatibility layer - also at runtime

### ISSUE THREAD

**Issue by casparvl** [EESSI/software-layer#52]
Currently, when we build in the software layer, we do that on top of the compatibility layer. That means that e.g. using a "system" python would mean: using the python from the compatibility layer.

At runtime, the same module would however use another "system" python: the one from the host. This could present problems...

We could see what happens if we use everything from the compat layer, and learn if that gives problems. Proposal is to do that for `2020.12`.

**Comment by boegel** [comment]
In #54 I'm adding `$EPREFIX/usr/bin` to `$PATH` in the init script.

I' not 100% convinced this is the right way forward, I think we want to have control over which commands get inherited from the compat layer vs which ones come from the host, but for now #54 makes sense (so we can see if we hit any problems with that approach).

Long term, I think only leveraging specific commands from the compat layer (by creating symlinks to `$EPREFIX/usr/bin`) may be better?

**Comment by boegel** [comment]
fixed in #54
