### ISSUE TITLE
Add the latest ReFrame to the list of installed software

### ISSUE THREAD

**Issue by casparvl** [EESSI/software-layer#67]
This would reduce reduces the amount of steps one needs to take to run the test suite (if the EESSI stack is mounted natively through CVMFS that is).

I did run into an issuewhen I installed ReFrame on `generoso` (while in the prefix environment), where it complained about missing pip (despite pip being one of the extensions listed by the ReFrame EasyConfig). I could resolve it by adding the `pip` egg to the `PYTHONPATH`, 
```
    'PYTHONPATH': ['external', 'lib/python3.8/site-packages/pip-20.2.4-py3.8.egg'],
```
but this felt like a very dirty solution somehow... Anyway, just sharing it in case you run into the same issue.

**Comment by boegel** [comment]
fixed in #76
