### ISSUE TITLE
Support for zsh

### ISSUE THREAD

**Issue by Flamefire** [EESSI/software-layer#702]
Currently there is only an `init/bash` script which doesn't work on e.g. `zsh` for obvious reasons.

Is the requirement of a bash shell documented already? Can other shells (as far as they are supported by lmod) also be supported?

Our users just asked about zsh in particular

**Comment by boegel** [comment]
@Flamefire Full support for `zsh` is in the works via https://github.com/EESSI/software-layer/pull/668

Very recently (see #667) we have included a module file to initialize your environment for using EESSI, so you can now also do this:

```
module use /cvmfs/software.eessi.io/init/modules/
module load EESSI/2023.06
```

The benefit here is that this should work across different types of shells (anything that Lmod supports), and that it's reversible (`module unload EESSI`).

There are some known issues though, see for example #694 
```

**Comment by ocaisa** [comment]
This is in the works, as of last week you can use EESSI as a module. Assuming you already have Lmod available
```
module use /cvmfs/software.eessi.io/init/modules
module load EESSI
```
We are working towards including best practices (i.e., implementing an Lmod family for local and EESSI software stacks so you don't accidentally mix them...which may or may not work depending on what you try to do).

**Comment by boegel** [comment]
@Flamefire BTW, a better channel to ask for help is the EESSI support portal , see https://www.eessi.io/docs/support

**Comment by ocaisa** [comment]
If Lmod is not available, as of last night this is now in place via
```
source /cvmfs/software.eessi.io/versions/2023.06/init/lmod/zsh
```

**Comment by ocaisa** [comment]
Again, this is _very_ new and will probably subject to some tweaking over the next few weeks

**Comment by ocaisa** [comment]
Closing this as done
