### ISSUE TITLE
Broken/weird filenames for tarballs created by eessi_container.sh script

### ISSUE THREAD

**Issue by bedroge** [EESSI/software-layer#712]
The tarballs in the job's `previous_tmp` subdirs are all named `-<timestamp>.tgz` . It's using `${REPOSITORY}` in the filename at https://github.com/EESSI/software-layer/blob/2023.06-software.eessi.io/eessi_container.sh#L851, but that's no longer defined after we merged https://github.com/EESSI/software-layer/pull/618.

Also, the script is using `tar cf`, i.e. without compression, while the extension `tgz` is used. We should either add an `z` option, or use `.tar`.

**Comment by boegel** [comment]
@trz42 @bedroge Can this be closed thanks to the changes in #714?

**Comment by bedroge** [comment]
> @trz42 @bedroge Can this be closed thanks to the changes in #714?

Yep, this has been fixed.
