### ISSUE TITLE
EESSI-extend doesn't load on systems which have `LMOD_EXACT_MATCH=yes`

### ISSUE THREAD

**Issue by casparvl** [EESSI/software-layer#746]
EESSI-extend just tries to load the default EasyBuild version. This doesn't work when a system requires `LMOD_EXACT_MATCH=yes`

```
{EESSI 2023.06} [casparl@tcn1 software-layer]$ module load EESSI-extend/2023.06-easybuild
-- Using /tmp/$USER as a temporary working directory for installations, you can override this by setting the environment variable WORKING_DIR and reloading the module (e.g., /dev/shm is a common option)
Configuring for use of EESSI_USER_INSTALL under /home/casparl/eessi
-- To create installations for EESSI, you _must_ have write permissions to /home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2
-- You may wish to configure a sources directory for EasyBuild (for example, via setting the environment variable EASYBUILD_SOURCEPATH) to allow you to reuse existing sources for packages.
Lmod has detected the following error:  These module(s) or extension(s) exist but cannot be loaded as requested: "EasyBuild"
   Try: "module spider EasyBuild" to see how to load the module(s).

Executing this command requires loading "EasyBuild" which failed while processing the following module(s):

    Module fullname                 Module Filename
    ---------------                 ---------------
    EESSI-extend/2023.06-easybuild  /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/modules/all/EESSI-extend/2023.06-easybuild.lua
```

(we enforce this on our system since we got tired of people relying on defaults and then complaining that their code ran differently when we installed some new version - and they simply weren't aware :))

One option would be to have the EasyBuild version as a suffix - in which case there would be multiple EESSI-extend modules. Alternatively, maybe the module can still be convinced to load a default (can a module change lmod config on the fly...?) version. Or at least print a somewhat more clear error.

Note that as a workaroud, I load an EasyBuild module first, then load `EESSI-extend`. That way, it works

**Comment by ocaisa** [comment]
I wonder if there is a way to ask Lmod what the default version of a package is? That would be enough

**Comment by ocaisa** [comment]
Maybe `latest("EasyBuild")` from https://lmod.readthedocs.io/en/latest/050_lua_modulefiles.html#modifier-functions-to-prereq-and-loads ?

**Comment by ocaisa** [comment]
Yes, that works, I'll make a PR
