### ISSUE TITLE
failing 'rstan' installation due to timezone issue?!

### ISSUE THREAD

**Issue by boegel** [EESSI/software-layer#79]
During the installation of `R-4.0.0-foss-2020a.eb` in the `2021.03` version of the software layer, the installation of `rstan` is failing with:

```
** R
** inst
** byte-compile and prepare package for lazy loading
Error in as.POSIXlt.character(x, tz, ...) :
  character string is not in a standard unambiguous format
Error: unable to load R code in package rstan
Execution halted
ERROR: lazy loading failed for package rstan
```

Others have reported this issue with `rstan` too, see https://github.com/stan-dev/rstan/issues/612.

The problem is easy to reproduce manually when starting `R`:

```
$ R
> as.POSIXct("1970-01-01 00:00.00 UTC")
Error in as.POSIXlt.character(x, tz, ...) :
  character string is not in a standard unambiguous format
```

Workaround in R:

```
> as.POSIXct("1970-01-01 00:00.00 UTC", tz='UTC')
[1] "1970-01-01 UTC"
```

Workaround using `$TZ`:

```
$ TZ=UTC R
> as.POSIXct("1970-01-01 00:00.00 UTC")
[1] "1970-01-01 UTC"
```

I worked around this in 86e5ca9 by setting `$TZ` to `UTC` when installing `R`.

**Comment by boegel** [comment]
This is related to not having `/etc/localtime` anymore in the `2021.03` compat layer, while it is there in `2020.12`:

```
$ cat /cvmfs/pilot.eessi-hpc.org/2020.12/compat/linux/x86_64/etc/localtime
TZif2-00TZif2-00
<-00>0
```

The problem can be fixed by symlinking the missing file to the host:

```
ln -s /etc/localtime /cvmfs/pilot.eessi-hpc.org/2021.03/compat/linux/x86_64/etc/localtime
```

**Comment by bedroge** [comment]
This has been solved in https://github.com/EESSI/compatibility-layer/pull/105.
