### ISSUE TITLE
ReFrame installation fails in 2021.03 pilot

### ISSUE THREAD

**Issue by boegel** [EESSI/software-layer#81]
`pip check` fails with:

```
keyring 23.0.0 has requirement importlib_metadata>=3.6, but you have importlib-metadata 2.0.0.
```

I'm not sure where it's picking up the `2.0.0` version of `importlib-metadata` from, that's not what's installed in the compat layer:

```
$ pip3 list | egrep 'pip|keyring|metadata'
importlib-metadata 3.7.3
keyring            23.0.0
pip                21.0.1
```

Somehow this only occurs when installing ReFrame, `pip check` works fine in the Prefix environment:

```
$ pip3 check
No broken requirements found.
```

We overlooked this initially because of a bug in the install script (see #82).

**Comment by boegel** [comment]
@victorusu @vkarak Does this happen to ring any bells for you?

**Comment by victorusu** [comment]
@teojgo, can you also take a look at this?

**Comment by vkarak** [comment]
I haven't seen that before, we are using `importlib_metadata==2.0.0` but not for a particular reason. Just because we had to pin the versions. We can bump it if needed.

**Comment by boegel** [comment]
Ah, indeed, it's installed as a part of ReFrame itself:

```
$ grep ^Version /cvmfs/pilot.eessi-hpc.org/2021.03/software/linux/x86_64/generic/software/ReFrame/3.4.1/external/importlib_metadata-2.0.0.dist-info/METADATA
Version: 2.0.0
```

Oh boy...

I'll patch that ReFrame easyconfig to make it install a newer version, and open a PR to ReFrame to bump to latest.

**Comment by vkarak** [comment]
On Tuesday we plan to release 3.5.2, so if you're not in hurry, you can wait until then, do the bump in our repo and update the EB recipe to 3.5.2.

**Comment by boegel** [comment]
I've added a workaround in the easyconfig for the current latest version of ReFrame (3.5.1), see https://github.com/easybuilders/easybuild-easyconfigs/pull/12511 .

We can install that one for now, and then update or also install ReFrame 3.5.2 once that's available (once @vkarak has opened a PR to EasyBuild for it ;) )
