### ISSUE TITLE
Add Spark to the pilot repo

### ISSUE THREAD

**Issue by bedroge** [EESSI/software-layer#90]
@JvD007 asked if it's possible to add (Py)Spark to the EESSI repo. There's an easyconfig for fosscuda 2020b:
https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/s/Spark/Spark-3.1.1-fosscuda-2020b.eb
As we don't support CUDA yet, we could probably convert this to a `foss 2020a` version.

**Comment by ocaisa** [comment]
The EB part of the request is in https://github.com/easybuilders/easybuild-easyconfigs/pull/12640

**Comment by bedroge** [comment]
Thanks @ocaisa!

He also requested Jupyter Notebooks, so I'll add your easyconfig for Spark and one for IPython to the build script, test it, and make a PR.
