### ISSUE TITLE
Qt5 from `2021.03` broken on kernels < 3.17

### ISSUE THREAD

**Issue by ocaisa** [EESSI/software-layer#99]
There is some problem with the `libQ5Core.so.5` available through EESSI `2021.03` on Zen2. It is not being picked when using `ldd` and executables from that installation fail to find it (even though the file does exist where one expects). The library also cannot be `LD_PRELOAD`ed

**Comment by ocaisa** [comment]
This is because the Qt5 build we have requires kernel 3.17:
```
[ocaisa@node1 all]$ readelf -n /cvmfs/pilot.eessi-hpc.org/2020.12/software/x86_64/amd/zen2/software/Qt5/5.14.1-GCCcore-9.3.0/lib/libQt5Core.so |grep Linux
    OS: Linux, ABI: 3.17.0
```

**Comment by ocaisa** [comment]
It looks like this can be fixed by some additional config options:
```
		-no-feature-statx	# bug 672856
		-no-feature-getentropy # needs kernel 3.17
		-no-feature-renameat2 # needs kernel 3.16
```
see https://github.com/ComputeCanada/gentoo-overlay/blob/main/dev-qt/qtcore/qtcore-5.12.5-r1.ebuild

**Comment by terjekv** [comment]
Great catch, but dear God how badly this sucks.

**Comment by ocaisa** [comment]
This is already known in the easyblock https://github.com/easybuilders/easybuild-easyblocks/blob/develop/easybuild/easyblocks/q/qt.py#L123 but there is no way to force that behaviour

**Comment by ocaisa** [comment]
Allowing to force this behaviour is done in https://github.com/easybuilders/easybuild-easyblocks/pull/2403

**Comment by boegel** [comment]
@ocaisa I think this can be closed?

**Comment by ocaisa** [comment]
Yes, fixed in eb
